inherit_gem:
  rubocul: rubocul_default.yml

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.0.3
  TargetRailsVersion: 7.0
  Exclude:
    - 'app/javascript/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'lib/tasks/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'

Style/Documentation:
  Enabled: false
